"""
Database configuration and ORM models for the wall-finish coverage system.

This module sets up the SQLAlchemy engine, session manager, and
declarative base class. It also defines ORM models representing
trajectory records, obstacles, planner parameters, forbidden
rectangles, and generated waypoints.

Author: Siddhant Gond
"""

from datetime import datetime, timezone
from sqlalchemy import (
    create_engine,
    Column,
    Integer,
    Float,
    DateTime,
    JSON,
    String,
)
from sqlalchemy.orm import sessionmaker, declarative_base

# ---------------------------------------------------------------------
# Database Configuration
# ---------------------------------------------------------------------

SQLALCHEMY_DATABASE_URL = "sqlite:///./trajectories.db"

engine = create_engine(
    SQLALCHEMY_DATABASE_URL,
    connect_args={"check_same_thread": False}  # Required for SQLite + multithreading
)

SessionLocal = sessionmaker(
    autocommit=False,
    autoflush=False,
    bind=engine
)

Base = declarative_base()


# ---------------------------------------------------------------------
# ORM Models
# ---------------------------------------------------------------------

class TrajectoryDB(Base):
    """
    Represents a trajectory generated by the coverage planner.
    Stores full metadata, input parameters, processed obstacles,
    and waypoints for visualization and further analysis.
    """

    __tablename__ = "trajectories"

    id = Column(Integer, primary_key=True, index=True)

    job_name = Column(String, nullable=True)

    created_at = Column(
        DateTime,
        default=lambda: datetime.now(timezone.utc),
        index=True
    )
    updated_at = Column(
        DateTime,
        default=lambda: datetime.now(timezone.utc),
        onupdate=lambda: datetime.now(timezone.utc),
    )

    # Wall details
    wall_width = Column(Float, nullable=False)
    wall_height = Column(Float, nullable=False)

    # Original inputs
    obstacles = Column(
        JSON,
        nullable=False,
        doc="Original obstacle list as provided by the user."
    )
    planner_params = Column(
        JSON,
        nullable=False,
        doc="Parameters used by the planner."
    )

    # Preprocessed obstacles
    forbidden_rects = Column(
        JSON,
        nullable=False,
        doc="Inflated and merged forbidden rectangles used internally."
    )

    # Output path
    waypoints = Column(
        JSON,
        nullable=False,
        doc="Generated list of ordered waypoints."
    )

    # Metadata
    meta = Column(
        JSON,
        nullable=False,
        doc="Path length, coverage fraction, warnings, planner version, etc."
    )

    status = Column(
        String,
        default="completed",
        doc="Job status: pending/running/completed/failed."
    )
    error_message = Column(
        String,
        nullable=True,
        doc="Error message if trajectory generation failed."
    )


# ---------------------------------------------------------------------
# Database Session Dependency
# ---------------------------------------------------------------------

def get_db():
    """
    Dependency that provides a database session for FastAPI routes.
    Ensures proper session closing after request is handled.
    """
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()
